### ISSUE TITLE
csanuragjain - Claim is done on deactivated plugin

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-telcoin-judging#14]
csanuragjain

medium

# Claim is done on deactivated plugin

## Summary
It seems that it is not checked whether a plugin is disabled before making a claim.

## Vulnerability Detail
1. Assume that plugin X was deactivated
2. Owner has still not removed the plugin
3. User immediately makes a claim using `claim` function which internally calls `_claim`
4. Now `_claim` does not check whether plugin is deactivated which means claim will be called over a deactivated plugin which was not expected

```solidity
function _claim(address account, address to, bytes calldata auxData) private returns (uint256) {
        // balance of `to` before claiming
        uint256 balBefore = IERC20Upgradeable(tel).balanceOf(to);

        // call claim on all plugins and count the total amount claimed
        uint256 total;
        bytes[] memory parsedAuxData = parseAuxData(auxData);
        for (uint256 i = 0; i < nPlugins; i++) {
            try IPlugin(plugins[i]).claim(account, to, parsedAuxData[i]) returns (uint256 xClaimed) {
                total += xClaimed;
            } catch  {
                emit PluginClaimFailed(plugins[i]);
            }
        }
...
}
```

## Impact
User can make claim from a disabled plugin which is not expected

## Code Snippet
https://github.com/sherlock-audit/2023-02-telcoin/blob/main/telcoin-audit/contracts/staking/StakingModule.sol#L281

## Tool used
Manual Review

## Recommendation
Before claiming amount in a plugin, it should be checked that plugin is not disabled

```solidity
function _claim(address account, address to, bytes calldata auxData) private returns (uint256) {
        // balance of `to` before claiming
        uint256 balBefore = IERC20Upgradeable(tel).balanceOf(to);

        // call claim on all plugins and count the total amount claimed
        uint256 total;
        bytes[] memory parsedAuxData = parseAuxData(auxData);
        for (uint256 i = 0; i < nPlugins; i++) {

if(IPlugin(plugin).deactivated()){
continue;
}

            try IPlugin(plugins[i]).claim(account, to, parsedAuxData[i]) returns (uint256 xClaimed) {
                total += xClaimed;
            } catch  {
                emit PluginClaimFailed(plugins[i]);
            }
        }
...
}
```

**Comment by amshirif** [comment]
Part of the reason that the `plugin.claim()` function is wrapped in a try{} catch{} block is for this very reason. If a plugin has been deactivated it will be skipped and noted by way of the `emit PluginClaimFailed(plugins[i])`.
https://github.com/sherlock-audit/2023-02-telcoin/blob/97b2bcd78740a870159b25d2f04806068c1c4c1f/telcoin-audit/contracts/staking/StakingModule.sol#L360-L366

**Comment by amshirif** [comment]
Addendum to https://github.com/sherlock-audit/2023-02-telcoin-judging/issues/14#issuecomment-1478566074: Above
The `deactivated` flag/function call can be used in multiple ways. It is left open-ended in order for future plugins to leverage it or not. A plugin itself might choose to reference its activation state. The plugin might throw an error when claim is called while it is deactivated. It might also, use this to stop accepting incoming rewards. The purpose of the call in the context of the staking contract is so that it cannot be removed if it is active. However, It might also be desired that a plugin is left attached to the staking contract with the desired purpose that users can continue to claim their rewards at a later date despite the program no longer accumulating rewards. This last case would describe the current set up. In the event that a plugin is deactivated it can be left for users to claim their rewards. If we wish to prevent users from claiming rewards that have been accumulated, it is recognized that the removal of the plugin must come in the same transaction as the deactivation of the plugin.

**Comment by hrishibhat** [comment]
Closing this based on the above comments as there is no check for plugin deactivation it is a design choice and the plugin code is out of scope. 
Also, even without the context of the plugin code, the add or remove plugin is an admin function. So the admin must make sure to deactivate+removeplugin in the same transaction in case they do not want claims to be made.
