### ISSUE TITLE
Bauer - If a plugins is removed user will not able to get rewards  from that plugin

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-telcoin-judging#30]
Bauer

high

# If a plugins is removed user will not able to get rewards  from that plugin

## Summary
If a plugins is removed user will not able to get rewards  from that plugin 

## Vulnerability Detail
The ```StakingModule``` contract allows user stakes some amount of TEL to earn potential rewards. User can call ```claim()``` to  claims yield from all plugins. However, if a plugin is removed user will not able to get rewards from that plugin 
```solidity
function _claimFromIndividualPlugin(address account, address to, address pluginAddress, bytes calldata auxData) private returns (uint256) {
        require(pluginsMapping[pluginAddress], "StakingModule::_claimFromIndividualPlugin: Provided pluginAddress is invalid");
        
        // balance of `to` before claiming
        uint256 balBefore = IERC20Upgradeable(tel).balanceOf(to);

        // xClaimed = "amount of TEL claimed from the plugin"
        uint256 xClaimed = IPlugin(pluginAddress).claim(account, to, parseAuxData(auxData)[pluginIndicies[pluginAddress]]);

        // we want to make sure the plugin did not return the wrong amount
        require(IERC20Upgradeable(tel).balanceOf(to) - balBefore == xClaimed, "The plugin did not send appropriate token amount");

        // only emit Claimed if anything was actually claimed
        if (xClaimed > 0) {
            emit Claimed(account, xClaimed);
        }

        return xClaimed;
    }
```

## Impact
 If a plugins is removed user will not able to get rewards

## Code Snippet
https://github.com/sherlock-audit/2023-02-telcoin/blob/main/telcoin-audit/contracts/staking/StakingModule.sol#L353-L377
https://github.com/sherlock-audit/2023-02-telcoin/blob/main/telcoin-audit/contracts/staking/StakingModule.sol#L543-L555
## Tool used

Manual Review

**Comment by amshirif** [comment]
The plugin code should have been provided in this repo but out of scope. This issue was brought up in the last audit and was fixed. The plugin itself has code that helps with this issue. Plugins are only to be removed when compromised or broken, not simply when a rewards system has concluded. Because of this, exiting, or a forced exit by way of automatically distributing funds, might be impossible or might distribute money to the bad actor. For this reason, if a plugin does have one of these issues it is deactivated. Once deactivated the funds can be removed and distributed manually. Funds cannot be removed if a plugin is not deactivated. It would not have been possible to know this since the plugin code was not provided.

**Comment by hrishibhat** [comment]
Closing based on the above comment
